
package com.test.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.4
 * Sat Apr 27 16:45:49 WIT 2013
 * Generated source version: 2.7.4
 */

@XmlRootElement(name = "helloName", namespace = "http://test.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "helloName", namespace = "http://test.com/")

public class HelloName {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

