<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="HelloService" targetNamespace="http://test.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://test.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://test.com/" schemaLocation="hello_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="helloName">
    <wsdl:part name="parameters" element="tns:helloName">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="helloNameResponse">
    <wsdl:part name="parameters" element="tns:helloNameResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Hello">
    <wsdl:operation name="helloName">
      <wsdl:input name="helloName" message="tns:helloName">
    </wsdl:input>
      <wsdl:output name="helloNameResponse" message="tns:helloNameResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HelloServiceSoapBinding" type="tns:Hello">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="helloName">
      <soap:operation soapAction="urn:HelloName" style="document"/>
      <wsdl:input name="helloName">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="helloNameResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HelloService">
    <wsdl:port name="HelloPort" binding="tns:HelloServiceSoapBinding">
      <soap:address location="http://localhost:8080/HelloPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
