
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package test;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-27T22:05:02.146+07:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloService",
                      portName = "HelloPort",
                      targetNamespace = "http://test.com/",
                      wsdlLocation = "file:/media/Data/workspace/MOA_services/WebContent/wsdl/hello.wsdl",
                      endpointInterface = "test.Hello")
                      
public class HelloImpl implements Hello {

    private static final Logger LOG = Logger.getLogger(HelloImpl.class.getName());

    /* (non-Javadoc)
     * @see test.Hello#helloName(java.lang.String  arg0 )*
     */
    public java.lang.String helloName(java.lang.String arg0) { 
        LOG.info("Executing operation helloName");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1240363259";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
