package test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-04-27T22:05:02.166+07:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://test.com/", name = "Hello")
@XmlSeeAlso({ObjectFactory.class})
public interface Hello {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "helloName", targetNamespace = "http://test.com/", className = "test.HelloName")
    @WebMethod(action = "urn:HelloName")
    @ResponseWrapper(localName = "helloNameResponse", targetNamespace = "http://test.com/", className = "test.HelloNameResponse")
    public java.lang.String helloName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
